name: CI/CD Deploy to EC2 (Nginx)

on:
  push:
    branches:
      - main   # Trigger deployment when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT || 22 }}
          script: |
            set -euxo pipefail

            # Ensure required packages
            sudo apt-get update -y
            sudo apt-get install -y nginx git rsync

            # Create web root if missing
            sudo mkdir -p /var/www/app

            # Clone or update repo
            if [ ! -d "/opt/cicd-demo-repo/.git" ]; then
              sudo rm -rf /opt/cicd-demo-repo
              sudo git clone --branch main "${{ secrets.REPO_URL }}" /opt/cicd-demo-repo
            else
              cd /opt/cicd-demo-repo
              sudo git fetch --all
              sudo git reset --hard origin/main
            fi

            # Sync app folder into /var/www/app
            sudo rsync -av --delete /opt/cicd-demo-repo/app/ /var/www/app/

            # Test and reload Nginx
            sudo nginx -t
            sudo systemctl reload nginx
